version: '3'

services:
  perforce:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./perforce-data:/perforce-data
      - ./dbs:/dbs
    environment:
      - P4PORT=1666
      - P4ROOT=/perforce-data
    ports:
      - "1666:1666"